######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 19 19:36:11 2024
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              build/Desktop-Debug/DateTimeIntervalProgram_autogen \
              build/Desktop-Debug/CMakeFiles/DateTimeIntervalProgram.dir \
              build/Desktop-Debug/CMakeFiles/DateTimeIntervalProgram_autogen.dir \
              build/Desktop-Debug/CMakeFiles/DateTimeIntervalProgram_autogen_timestamp_deps.dir \
              build/Desktop-Debug/DateTimeIntervalProgram_autogen/include \
              build/Desktop-Release/CMakeFiles/DateTimeIntervalProgram.dir \
              build/Desktop-Release/CMakeFiles/DateTimeIntervalProgram_autogen.dir \
              build/Desktop-Release/CMakeFiles/DateTimeIntervalProgram_autogen_timestamp_deps.dir \
              build/Desktop-Release/DateTimeIntervalProgram_autogen/include \
              build/Desktop-Debug/CMakeFiles/3.29.2/CompilerIdCXX \
              build/Desktop-Release/CMakeFiles/3.29.2/CompilerIdCXX
INCLUDEPATH += .

# Input
HEADERS += datetimeinterval.h \
           datetimeintervalform.h \
           mainwindow.h \
           ui_DateTimeIntervalForm2.h \
           ui_mainwindow2.h \
           build/Desktop-Debug/DateTimeIntervalProgram_autogen/EWIEGA46WW/moc_mainwindow.cpp
FORMS += DateTimeIntervalForm.ui mainwindow.ui
SOURCES += datetimeinterval.cpp \
           datetimeintervalform.cpp \
           main.cpp \
           mainwindow.cpp \
           build/Desktop-Debug/DateTimeIntervalProgram_autogen/mocs_compilation.cpp \
           build/Desktop-Debug/CMakeFiles/3.29.2/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Desktop-Release/CMakeFiles/3.29.2/CompilerIdCXX/CMakeCXXCompilerId.cpp
TRANSLATIONS += DateTimeIntervalProgram_en_US.ts \
                build/Desktop-Debug/CMakeFiles/DateTimeIntervalProgram.dir/compiler_depend.ts \
                build/Desktop-Debug/CMakeFiles/DateTimeIntervalProgram_autogen.dir/compiler_depend.ts \
                build/Desktop-Debug/CMakeFiles/DateTimeIntervalProgram_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/Desktop-Release/CMakeFiles/DateTimeIntervalProgram.dir/compiler_depend.ts \
                build/Desktop-Release/CMakeFiles/DateTimeIntervalProgram_autogen.dir/compiler_depend.ts \
                build/Desktop-Release/CMakeFiles/DateTimeIntervalProgram_autogen_timestamp_deps.dir/compiler_depend.ts
